
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true




      routes:
        - id: EMPLOYEE-SERVICE
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/employee/**
          filters:
            - AuthenticationFilter


        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/api/department/**
          filters:
            - AuthenticationFilter
            -
        - id: MS-SECURITY
          uri: lb://MS-SECURITY
          predicates:
            -Path=/api/auth/**













server:
  port: 9191
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
